name: fanni
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations: 
    sdk: flutter
  retrofit: ^4.4.0  
  pretty_dio_logger: ^1.4.0
  freezed_annotation: ^2.2.0
  dio: ^5.5.0+1
  intl: ^0.20.2
  equatable: ^2.0.5
  flutter_svg: ^2.0.3
  get_it: ^7.7.0
  go_router: ^14.2.3
  dartz: ^0.10.1
  connectivity_plus: ^6.1.3
  provider: ^6.0.2
  shared_preferences: ^2.0.15
  cached_network_image_plus: ^0.0.4
  intl_phone_number_input: ^0.7.4
  shimmer: ^3.0.0
  image_picker: ^1.0.0
  flutter_dotenv: ^5.2.1
  gap: ^3.0.1
  logger: ^2.5.0
  google_fonts: ^4.0.3
  pinput: ^5.0.1
  qr_code_scanner_plus: ^2.0.10+1
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html: ^0.15.3
  url_launcher: ^6.3.1
  flutter_smart_dialog: ^4.9.7+9
  local_auth: ^2.1.7
  permission_handler: ^12.0.0+1
  smooth_page_indicator: ^1.2.1
  item_count_number_button: ^1.9.2
  file_picker: ^8.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  bot_toast: ^4.1.3
  loading_animation_widget: ^1.3.0
  syncfusion_flutter_charts: ^29.2.5
  awesome_notifications: ^0.10.1
  confetti: ^0.8.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  jiffy: ^6.3.2
  fl_chart: ^1.1.1
  video_player: ^2.10.0
  webview_flutter:
  http:
  photo_view: ^0.15.0
  flutter_html: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.4.0
  build_runner: ^2.7.0
  open_file: ^3.0.1
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  retrofit_generator: '>=8.0.0 <10.0.0'
  

dependency_overrides:
  build_runner: ^2.4.5


flutter_assets:
  assets_path: assets/
  output_path: lib/core/constant/
  filename: app_image.dart
  field_prefix:

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/image/
    - assets/icon/
 

  fonts:
    - family: Jannalt
      fonts:
        - asset: assets/fonts/JANNALT-REGULAR.TTF
    - family: Georgia
      fonts:
        - asset: assets/fonts/Georgia.ttf